app/blueprints/dashboard/views.py
from flask import Blueprint, render_template, request, redirect, send_file, url_for, jsonify, redirect, g

from app.dataLoader import loadInventoryData
from app.models import tblwidth
import os
from app.extensions import db
from sqlalchemy import text
import pandas as pd
from datetime import datetime

dashboard_blueprint = Blueprint("dashboard", __name__, template_folder="templates")


@dashboard_blueprint.route("/")
def home():   
    return render_template('dashboard.html')

app/blueprints/home/views.py
from flask import Blueprint, render_template, request, redirect, send_file, url_for, jsonify, redirect

home_blueprint = Blueprint("home", __name__, template_folder="templates")

@home_blueprint.route("/")
def home():
    return render_template('home.html')

app/templates/about.html
{% extends 'base.html' %}
{% set active_page='about' %}
{% block pageTitle %}
About
{%endblock%}
{% block pageContent %}
<h1 class="primary">I am home</h1>
{% endblock %}

app/templates/base.html
{% from 'nav.html' import display_nav %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block pageTitle %}{%endblock%}</title>
    <script src="https://unpkg.com/htmx.org@1.9.6"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />

    <link href="https://fonts.googleapis.com/icon?family=Material+Symbols+Outlined" rel="stylesheet" />
    <!-- Nucleo Icons -->
    <link href="{{url_for('static', filename='css/nucleo-icons.css')}}" rel="stylesheet" />

    <link href="{{url_for('static', filename='css/nucleo-svg.css')}}" rel="stylesheet" />

    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <link href="{{url_for('static', filename='css/nucleo-svg.css')}}" rel="stylesheet" />

    <!-- CSS Files -->
    <!-- <link id="pagestyle" href="{{url_for('static', filename='scss/material-dashboard.css')}}" rel="stylesheet" />-->

    <script src="{{url_for('static', filename='js/extruderFilter.js')}}" type="text/javascript"></script>
    <script src="{{url_for('static', filename='js/filedownload.js')}}" type="text/javascript"></script>

    <link rel="stylesheet" href="{{url_for('static', filename='scss/styles.css')}}" />

</head>

<body>
    {{display_nav()}}
    <hr>
    <div class="container-fluid">
        {% with messages=get_flashed_messages(with_categories=True) %}
        {% if messages %}
        {% for type, content in messages %}
        <div class="alert alert-{{type}} alert-dismissible fade show" role="alert">
            <strong>{{type}} </strong> {{content}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
    </div>
    <div class="container-fluid">
        {% block pageContent %}
        {% endblock %}
    </div>

    <!--   Core JS Files   -->
    <script src="{{url_for('static', filename='js/core/popper.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/core/bootstrap.min.js')}}"></script>

    <!-- Plugin for the charts, full documentation here: https://www.chartjs.org/ -->
    <script src="{{url_for('static', filename='js/plugins/chartjs.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/plugins/Chart.extension.js')}}"></script>

    <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
     <!-- <script src="{{url_for('static', filename='js/material-dashboard.min.js')}}"></script>-->
    
</body>

</html>

app/templates/chart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- chart.js CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.3.2/chart.min.js"
     integrity="sha512-VCHVc5miKoln972iJPvkQrUYYq7XpxXzvqNfiul1H4aZDwGBGC0lq373KNleaB2LpnC2a/iNfE5zoRYmB4TRDQ==" 
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='scss/styles.css')}}" />
    <script src="{{url_for('static', filename='js/htmx.min.js')}}" type="text/javascript"></script>
</head>
<body>
    <div class="container">

    </div>
    <canvas id="myChart" max-width="50" max-height="50"></canvas>
    <script>
    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: ['Black', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
            datasets: [{
                label: '# of Length',
                data: [1200, 1900, 300, 500, 20, 300],
                backgroundColor: [
                    'rgba(0, 0, 12, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });
    </script>
</body>
</html>

app/templates/displayTable.html
<table class="table">
    <tr class="table_header">
        {% for header in headings %}
        <th class="table_cell">{{header}}</th>
        {% endfor %}
    </tr>
    {% for row in data %}
    <tr class="table_row">
        {% for cell in row %}
        <td class="table_cell">{{cell}}</td>
        {% endfor %}
    </tr>
    {% endfor %}
</table>

app/templates/home.html
{% extends 'base.html' %}
{% set active_page='home' %}
{% block pageTitle %}
Home
{%endblock%}
{% block pageContent %}
<h1 class="primary">I am home new page</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% set active_page='index' %}
{% block pageTitle %}
Index
{%endblock%}
{% block pageContent %}
<h1 class="primary">I am index page</h1>
{% endblock %}

app/templates/macroTable.html
{% macro heading_row(headings) %}
<tr class="table_header">
    {% for header in headings %}
    <th class="table_cell">{{header}}</th>
    {% endfor %}
</tr>
{% endmacro %}

{% macro data_rows(data) %}
{% for row in data %}
<tr class="table_row">
    {% for cell in row %}
    <td class="table_cell">{{cell}}</td>
    {% endfor %}
</tr>
{% endfor %}
{% endmacro %}

{% macro display_table(headings, data) %}
    <table class="table">
        {{heading_row(headings)}}
        {{data_rows(data)}}
    </table>
{% endmacro %}

{% macro create_site_link(link, displayText) %}
    <a href="{{url_for(link)}}">{{displayText}}</a>
{% endmacro %}

{% macro every_page_header(headerText) %}
<div style="border-radius:4px; height: 3em; background-image: linear-gradient(195deg, #CAD2C5, #84A98C)">
    <span class="px-2 display-6 mask opacity-6">{{headerText}}</span>
</div>
{%endmacro %}

app/templates/nav.html
{% macro display_nav() %}
<nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{url_for('home.home')}}">Inside the Spectrum</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link {{'active' if active_page=='home' else '' }}" aria-current="page" href="{{url_for('home.home')}}">Home</a>
          </li>           
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('dashboard.home')}}">Dashboard</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Admin
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Reports</a></li>
              <li><a class="dropdown-item" href="#">Features</a></li>
              <li><a class="dropdown-item" href="#">Contact US</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  
{% endmacro %}

app/templates/table.html
{% from 'macroTable.html' import display_table %}
{% extends 'base.html' %}
{% set active_page='index' %}
{% block pageTitle %}
Table
{%endblock%}
{% block pageContent %}
<h1 class="primary">I am Table Page</h1>
    {{display_table(heading, data)}}
{% endblock %}